# Generated by Django 5.0.6 on 2026-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='why_others_lost',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelresponse',
            name='why_not_winner',
            field=models.TextField(blank=True),
        ),
    ]
